{% set name = "hjson-py" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hjson/hjson-{{ version }}.tar.gz
  sha256: 55af475a27cf83a7969c808399d7bccdec8fb836a07ddbd574587593b9cdcf75

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - hjson = hjson.tool:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - hjson
  commands:
    - pip check
    - hjson --help
  requires:
    - pip

about:
  home: http://github.com/hjson/hjson-py
  license: MIT OR AFL-2.1
  license_family: MIT
  license_file: LICENSE.txt
  summary: Hjson, a user interface for JSON.
  description: |
    Hjson is a syntax extension to JSON. It is intended to be used like a
    user interface for humans, to read and edit before passing the JSON
    data to the machine.
  doc_url: https://hjson.github.io/
  dev_url: https://github.com/hjson/hjson-py

extra:
  recipe-maintainers:
    - groodt
    - weiji14
